[package]
name = "chipioindustries/random-selection"
description = "A module for selecting a random item from a weighted list."
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.exe", "aftman", "*.zip"]

[dependencies]
t = "osyrisrblx/t@3.0.0"
Llama = "chipioindustries/llama@1.2.4"
TestEZ = "roblox/testez@0.4.1"
